// ---------- Enums ----------
// enum Leading comment
enum Corpus
{
		UNIVERSAL = 0, 
		WEB = 1, 
		IMAGES = 2, 
		LOCAL = 3, 
		NEWS = 4, 
		PRODUCTS = 5, 
		VIDEO = 6
};
// ---------- Messages ----------
// Some message
enum eDonkey
{
	// Some filed docs
	eHi[256]
};

enum eFunky
{
		eMonkey_msg,
		eDokey_msg
};

enum eSomeRPCRequest
{
		eId,
		eName[256]
};

enum eSomeRPCResponse
{
		eResult[256]
};

